### ISSUE TITLE
Error of 'std::out_of_range'

### ISSUE THREAD

**Issue by PoPdark** [hlinhn/read-pbstream#1]
Hey, how are you doing. My problem is to edit the .pbstream file and delete the specific submap. Once I thought it is not hard, but I've tried a lot and make no progress. Until I saw your 'filter_node.cc', which is exactly I need, I relized it is impossible for me to finish the job now. So may you please offer me some help?

Here is my error: 

Submap count: 79 77
6958 5530 
Node count: 2811 2775
Add constraints
terminate called after throwing an instance of 'std::out_of_range'
  what():  map::at
Aborted (core dumped)**

I located the error is occuring in the following block, but I can't figure the reson:

  **std::cout << "Add constraints\n";
  for (const auto& constraint : pose_graph_proto.constraint())
  {
    if (constraint.tag() != mapping::proto::PoseGraph::Constraint::INTRA_SUBMAP)
    {
      continue;
    }
    mapping::NodeId node_id {constraint.node_id().trajectory_id(), constraint.node_id().node_index()};
    mapping::SubmapId submap_id {constraint.submap_id().trajectory_id(), constraint.submap_id().submap_index()};
    if (excluded_submaps.count(submap_id) > 0)
    {
      continue;
    }
    if (excluded_nodes.count(node_id) > 0)
    {
      continue;
    }
    pose_graph.AddNodeToSubmap(node_id, submap_id);
  }**

My sincerest thanks.

**Comment by hlinhn** [comment]
Hi, thank you for your interest in the project. I haven't worked on this for a while so I can only provide some suggestions. From the error report it seems like the pose graph could not find the `submap_id` as supplied by the constraint (in `AddNodeToSubmap` function). That seems strange but maybe it could happen for later submap that has not been finalized, in which case it is probably safe to just ignore those nodes and submaps. I would suggest to check to see if this is indeed the case and if so, just do a simple try-catch to get rid of it. Hope it helps.

**Comment by PoPdark** [comment]
Hey, thank you for your suggestions and I tried to fix this error according to that.
I tried to skip the wrong part of the function using:

  **for (const auto& constraint : pose_graph_proto.constraint())
  {
    try
    {
      if (constraint.tag() != mapping::proto::PoseGraph::Constraint::INTRA_SUBMAP)
      {
        continue;
      }
      mapping::NodeId node_id {constraint.node_id().trajectory_id(), constraint.node_id().node_index()};
      mapping::SubmapId submap_id {constraint.submap_id().trajectory_id(), constraint.submap_id().submap_index()};
      if (excluded_submaps.count(submap_id) > 0)
      {
        continue;
      }
      if (excluded_nodes.count(node_id) > 0)
      {
        continue;
      }
      pose_graph.AddNodeToSubmap(node_id, submap_id);
    }
    catch (std::out_of_range& e)
    {
      std::cout << "WARNING: submap ignored" << std::endl;
    }
  }**
  
It didn't work, I was confused and I tried to remove the codes inside the cyclic, the program executed completely:

  **for (const auto& constraint : pose_graph_proto.constraint())
  {
//empty
  }**

I am doing so because according to your advise, I should not skip the whole cyclic. So why is that.

**Comment by PoPdark** [comment]
Hey, thank you for your suggestions and I tried to fix this error according to that.
I tried to skip the wrong part of the function using:

**for (const auto& constraint : pose_graph_proto.constraint())
{
try
{
if (constraint.tag() != mapping::proto::PoseGraph::Constraint::INTRA_SUBMAP)
{
continue;
}
mapping::NodeId nfor (const auto& constraint : pose_graph_proto.constraint())
{
try
{
if (constraint.tag() != mapping::proto::PoseGraph::Constraint::INTRA_SUBMAP)
{
continue;
}
mapping::NodeId node_id {constraint.node_id().trajectory_id(), constraint.node_id().node_index()};
mapping::SubmapId submap_id {constraint.submap_id().trajectory_id(), constraint.submap_id().submap_index()};
if (excluded_submaps.count(submap_id) > 0)
{
continue;
}
if (excluded_nodes.count(node_id) > 0)
{
continue;
}
pose_graph.AddNodeToSubmap(node_id, submap_id);
}
catch (std::out_of_range& ode_id {constraint.node_id().trajectory_id(), constraint.node_id().node_index()};
mapping::SubmapId submap_id {constraint.submap_id().trajectory_id(), constraint.submap_id().submap_index()};
if (excluded_submaps.count(submap_id) > 0)
{
continue;
}
if (excluded_nodes.count(node_id) > 0)
{
continue;
}
pose_graph.AddNodeToSubmap(node_id, submap_id);
}
catch (std::out_of_range& e)
{
std::cout << "WARNING: submap ignored" << std::endl;
}
}**

It didn't work, I was confused and I tried to remove the codes inside the cyclic, the program executed completely:

**for (const auto& constraint : pose_graph_proto.constraint())
{
//empty
}**

I am doing so because according to your advise, I should not skip the whole cyclic. I just found that the try{}catch(...){} block can't catch the exception and it it weird. I found your codes has the same error catching block, am I wrong with that?

**Comment by PoPdark** [comment]
![image](https://github.com/hlinhn/read-pbstream/assets/23391279/b99504e7-9a32-40fb-98ad-6d19499af2a0)
The error is occuring in this line, I try to catch the exception but it also have no use.

**Comment by hlinhn** [comment]
Can you be more specific? What do you mean it has no use? The previous comment was just my guess, it would be better to use gdb to understand exactly where the error came from.

**Comment by PoPdark** [comment]
Sorry for the fuzzy, I can't understand the problem myself right now. I ran the codes for thress times and each got different error. :-) 
![image](https://github.com/hlinhn/read-pbstream/assets/23391279/3d930536-8493-41df-bf34-2afe1e8b12a7)

**Comment by hlinhn** [comment]
That could happen if your output pipe is not flushed. As I have commented earlier, the best way is to use gdb to see exactly where the error happens

**Comment by PoPdark** [comment]
I am trying to find the problem through pdb debugging, but it is still difficult. Does this have anything to do with the fact that I'm building a 2d map.

**Comment by hlinhn** [comment]
I have never tried it with 2D map, it is possible that there are some differences I am not aware of. Does this happen for every node that you tried to delete and for all maps?

**Comment by PoPdark** [comment]
After deleting all the maps, the program ended correctly. Thank you very much for your answer. But the bad new is that I still have a long way to go...

**Comment by hlinhn** [comment]
Maybe you misunderstood my question - I meant to ask if the problem happens for any node that you try to delete (for example, there are 10 nodes in the map, does this only happen if you delete a specific node or any of the 10 can trigger it)?

**Comment by PoPdark** [comment]
Sorry for my misunderstanding. I've tried it a few times, and I think it can be triggered by any node.

**Comment by PoPdark** [comment]
Thank you very much for your patience, this error was indeed caused by the 3d pose_graph, I fixed the issue after changing it to 2d.
